---
title: 'Supplemental Materials #1: Illustrations using a dataset from Nohe et al.
  (Table A1; 2015)'
author: 'Mike W.-L. Cheung'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    toc: yes
    keep_tex: true
  html_document:
    keep_md: yes
    self_contained: yes
    theme: united
    toc: yes 
  word_document:
    toc: no
---

# Read the data and display the sample characteristics
```{r, message=FALSE}
## Required packages
lib2install <- c("lavaan", "semPlot", "metaSEM")

## Install them automatically if they have not been installed in your computer yet.
for (i in lib2install) {
  if (!(i %in% rownames(installed.packages()))) install.packages(i)
}

# Load the libraries for the analysis.
library(lavaan)
library(metaSEM)
library(semPlot)

## Correlation matrices
Nohe15A1$data

## Sample sizes
Nohe15A1$n

## Number of studies
pattern.na(Nohe15A1$data, show.na = FALSE)

## Sample sizes for each correlation coefficient
pattern.n(Nohe15A1$data, Nohe15A1$n)

## Sample sizes
summary(Nohe15A1$n)

## Histogram of the sample sizes
hist(Nohe15A1$n, main="Distribution of the sample sizes",
      xlab="Sample size", ylab="Count", col="blue", breaks=10)
```

# FIMASEM
```{r, warning=FALSE}
## Set seed for reproducibility
set.seed(39128482)

## Average the correlation coefficients with the univariate-r approach
uni1 <- uniR1(Nohe15A1$data, Nohe15A1$n)
uni1

## Generate random correlation matrices with parametric bootstrap
boot.cor <- bootuniR1(uni1, Rep=500)

## Display the summary of the generated correlation matrices
summary(boot.cor)

## Proposed saturated model
model1 <- 'W2 + S2 ~ W1 + S1'

boot1.fit <- bootuniR2(model=model1, data=boot.cor, n=uni1$n.harmonic)
summary(boot1.fit)

## Proposed model with equal regression coefficients
model2 <- 'W2 ~ Same*W1 + Cross*S1
           S2 ~ Cross*W1 + Same*S1
           W1 ~~ Cor1*S1
           W2 ~~ Cor2*S2'

boot2.fit <- bootuniR2(model=model2, data=boot.cor, n=uni1$n.harmonic)
summary(boot2.fit)
```

# TSSEM
```{r, warning=FALSE}
rand1 <- tssem1(Nohe15A1$data, Nohe15A1$n, method="REM", RE.type="Diag")
summary(rand1)

## SDs of the correlations (heterogeneity)
sqrt(coef(rand1, select="rand"))

## Cross-lagged panel model
model3 <- 'W2 ~ W2W*W1 + S2W*S1
           S2 ~ W2S*W1 + S2S*S1
           W1 ~~ W1cS1*S1
           W2 ~~ W2cS2*S2
           W1 ~~ 1*W1
           S1 ~~ 1*S1'

## Convert the lavaan model to the RAM model
RAM1 <- lavaan2RAM(model3, obs.variables=c("W1", "S1", "W2", "S2"))

rand2a <- tssem2(rand1, Amatrix=RAM1$A, Smatrix=RAM1$S)
summary(rand2a)

## Plot the model
my.plot1 <- meta2semPlot(rand2a)
semPaths(my.plot1, whatLabels="est", sizeMan=8, edge.label.cex=1.5, 
         color="yellow", edge.color = "black", weighted=FALSE)

## Model with equal regression coefficients
model4 <- 'W2 ~ Same*W1 + Cross*S1
           S2 ~ Cross*W1 + Same*S1
           W1 ~~ W1cS1*S1
           W2 ~~ W2cS2*S2
           W1 ~~ 1*W1
           S1 ~~ 1*S1'

RAM2 <- lavaan2RAM(model4, obs.variables=c("W1", "S1", "W2", "S2"))

rand2b <- tssem2(rand1, Amatrix=RAM2$A, Smatrix=RAM2$S)
summary(rand2b)

my.plot2 <- meta2semPlot(rand2b)
semPaths(my.plot2, whatLabels="est", sizeMan=8, edge.label.cex=1.5, 
         color="yellow", edge.color = "black", weighted=FALSE)

sessionInfo()
```





