all: Nohe2015 Gnambs2018

Nohe2015: Nohe2015.Rmd
	R --no-save --no-restore -e "library(rmarkdown); render('Nohe2015.Rmd', html_document(keep_md=TRUE))"

Gnambs2018: Gnambs2018.Rmd
	R --no-save --no-restore -e "library(rmarkdown); render('Gnambs2018.Rmd', html_document(keep_md=TRUE))"
