---
title: "MASEM on Gnambs et al. (2018)"
author: "Suzanne Jak and Mike Cheung"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    keep_md: yes
    self_contained: yes
    theme: united
    toc: yes
  pdf_document:
    toc: no
  word_document: default
editor_options: 
  chunk_output_type: console
---

# Data preparation  
```{r, message=FALSE}
library(metaSEM)

## Create a new dataset without missing value in Individualism
index_na <- is.na(Gnambs18$Individualism)
Gnambs18 <- lapply(Gnambs18, function(x) x[!index_na])

## Select data with the correlation matrices, i.e., exclude studies with only factor loadings
index <- Gnambs18$CorMat==1
Gnambs18 <- lapply(Gnambs18, function(x) x[index])

## Create a dataframe with the data and the asymptotic variances and covariances (acov)
my.df <- Cor2DataFrame(Gnambs18$data, Gnambs18$n, acov = "weighted")

## Add the standardized individualism as the moderator
## Standardization of the moderator improves the convergence.
my.df$data <- data.frame(my.df$data,
                         Individualism=scale(Gnambs18$Individualism),
                         check.names=FALSE)
summary(my.df)
```

# One-Stage MASEM
## Bifactor model without moderation
```{r, cache=TRUE}
## Specify the bifactor model

model0 <- "G =~  g1*I1 + g2*I2 + g3*I3 + g4*I4 + g5*I5 + 
                 g6*I6 + g7*I7 + g8*I8 + g9*I9 + g10*I10
          POS =~ p1*I1 + p3*I3 + p4*I4 + p7*I7 + p10*I10
          NEG =~ n2*I2 + n5*I5 + n6*I6 + n8*I8 + n9*I9"

RAM0 <- lavaan2RAM(model0, obs.variables = paste0("I", 1:10))
RAM0

## Create matrices with implicit diagonal constraints
M0 <- create.vechsR(A0=RAM0$A, S0=RAM0$S, F0=RAM0$F)

## Create heterogeneity variances
T0 <- create.Tau2(RAM=RAM0, RE.type="Diag", Transform="expLog", RE.startvalues=0.05)

## Fit the bifactor model with One-Stage MASEM
fit0 <- osmasem(model.name="No moderator", Mmatrix=M0, Tmatrix=T0, data=my.df)
summary(fit0, Saturated=TRUE)

## SRMR
osmasemSRMR(fit0)

## Estimated Tau2
diag(VarCorr(fit0))
```

## Bifactor model  with `Individualism` as a moderator on the A matrix
```{r, error=TRUE,, cache=TRUE}
## Create the A1 matrix with moderator effects of "Individualism"
Ax1 <- RAM0$A
Ax1[grep("\\*", Ax1)] <- "0*data.Individualism"
Ax1

## Create matrices with implicit diagonal constraints
M1 <- create.vechsR(A0=RAM0$A, S0=RAM0$S, F0=RAM0$F, Ax=Ax1)

## Fit the bifactor model with moderator
fit1 <- osmasem(model.name="Moderation by individualism", Mmatrix=M1, Tmatrix=T0, data=my.df)
summary(fit1)

## Get the R2
osmasemR2(fit1, fit0)

## Compare the models with and without moderator
anova(fit1, fit0)

## Get the estimated A0 (intercepts of factor loadings) and 
## A1 (regression coefficients of moderator on factor loadings)
A0 <- mxEval(A0, fit1$mx.fit)
A0
A1 <- mxEval(A1, fit1$mx.fit)
A1

# To calculate simple slopes
## Compute the estimated A matrix at -1SD (-1) of the standardized individualism
A0 - A1

## Compute the estimated A matrix at 0 (mean) of the standardized individualism
A0

## Compute the estimated A matrix at +1SD (+1) of the standardized individualism
A0 + A1
```


# TSSEM
## Bifactor model without moderation
```{r,, cache=TRUE}
# Stage 1 analysis with TSSEM
overall_stage1_tssem.fit <- tssem1(Gnambs18$data, Gnambs18$n, 
                                   method="REM", RE.type="Diag")
summary(overall_stage1_tssem.fit)

# Stage 2 analysis with TSSEM
overall_stage2_tssem.fit <- tssem2(overall_stage1_tssem.fit, Amatrix = RAM0$A, 
                                   Smatrix = RAM0$S, Fmatrix = RAM0$F)
summary(overall_stage2_tssem.fit)

plot(overall_stage2_tssem.fit, col="green")
```

## Subgroup analysis
```{r}
# Data for studies with individualism below the mean
data_g1 <- Gnambs18$data[my.df$data$Individualism < 0 ]
n_g1 <- Gnambs18$n[my.df$data$Individualism < 0 ]

# Data for studies with individualism above or equal the mean
data_g2 <- Gnambs18$data[my.df$data$Individualism >= 0 ]
n_g2 <- Gnambs18$n[my.df$data$Individualism >= 0 ]
```

### Fitting the Stage 1 model in two subgroups
```{r, message=FALSE, , cache=TRUE}
## Stage 1 analysis per subgroup (random-effects analysis)
stage1_g1.fit <- tssem1(Cov = data_g1, n = n_g1, method = "REM", RE.type = "Diag")
stage1_g2.fit <- tssem1(Cov = data_g2, n = n_g2, method = "REM", RE.type = "Diag")
```

### Fitting the Stage 2 bifactor model in both subgroups
```{r}
## Stage 2 analysis per subgroup (random-effect analysis)
stage2_g1.fit <- tssem2(stage1_g1.fit, Amatrix=RAM0$A, 
                        Smatrix=RAM0$S, Fmatrix=RAM0$F)

stage2_g2.fit <- tssem2(stage1_g2.fit, Amatrix=RAM0$A, 
                        Smatrix=RAM0$S, Fmatrix=RAM0$F)

summary(stage2_g1.fit)
summary(stage2_g2.fit)
```


```{r}
# Create matrices for subgroup analyses (same labels for factor loadings, 
# but not for residual variances)
CFAmodel.g2 <- 'G =~   g1*I1 + g2*I2 + g3*I3 + g4*I4 + g5*I5 + 
                       g6*I6 + g7*I7 + g8*I8 + g9*I9 + g10*I10
                POS =~ p1*I1 + p3*I3 + p4*I4 + p7*I7 + p10*I10
                NEG =~ n2*I2 + n5*I5 + n6*I6 + n8*I8 + n9*I9
                
                # Residual variances
                I1 ~~ hight1*I1
                I2 ~~ hight2*I2
                I3 ~~ hight3*I3
                I4 ~~ hight4*I4
                I5 ~~ hight5*I5
                I6 ~~ hight6*I6
                I7 ~~ hight7*I7
                I8 ~~ hight8*I8
                I9 ~~ hight9*I9
                I10 ~~ hight10*I10'

RAM0.g2 <- lavaan2RAM(CFAmodel.g2, obs.variables=paste0("I",1:10))


# Create the models for the two groups, make sure to set the argument run=FALSE
stage2_g1 <- tssem2(stage1_g1.fit, Amatrix=RAM0$A, Smatrix=RAM0$S, 
                    Fmatrix=RAM0$F, run=FALSE, model.name="low")

stage2_g2 <- tssem2(stage1_g2.fit, Amatrix=RAM0.g2$A, Smatrix=RAM0.g2$S, 
                    Fmatrix=RAM0.g2$F, run=FALSE, model.name="high")


# Create the multigroup model
stage2_constrained <- mxModel(model="same_loadings", stage2_g1, stage2_g2,
                              mxFitFunctionMultigroup(c("low", "high")))

# Fit multigroup model with equality constraints
Stage2_constrained.fit <- mxRun(stage2_constrained, intervals=FALSE)


# load function from website
source("http://www.suzannejak.nl/subgroup.functions.R")

# Make a list of the fitted models in the separate groups
submodels.fit <- list(stage2_g1.fit,stage2_g2.fit)

# Ask for summary, compare fit of constrained and unconstrained model
subgroup.summary(submodels.fit,Stage2_constrained.fit)
```

### Plots of factor loadings in subgroups
```{r}
# General factor (red = low individualism, blue = high individualism)
loadings.general.low <- c(stage2_g1.fit$mx.fit$Amatrix$values[1:10,11])
loadings.general.high <- c(stage2_g2.fit$mx.fit$Amatrix$values[1:10,11])

plot(loadings.general.low, type = "p", pch = 16, col = "red", ylim = c(-.1,1))
points(loadings.general.high, type = "p", pch = 17, col = "blue")

# Positive factor(red = low individualism, blue = high individualism)
loadings.positive.low <- c(stage2_g1.fit$mx.fit$Amatrix$values[c(1,3,4,7,10),13])
loadings.positive.high <- c(stage2_g2.fit$mx.fit$Amatrix$values[c(1,3,4,7,10),13])

plot(loadings.positive.low, type = "p", pch = 16, col = "red", ylim = c(-.1,1))
points(loadings.positive.high, type = "p", pch = 17, col = "blue")

# Negative factor (red = low individualism, blue = high individualism)
loadings.negative.low <- c(stage2_g1.fit$mx.fit$Amatrix$values[c(2,5,6,8,9),12])
loadings.negative.high <- c(stage2_g2.fit$mx.fit$Amatrix$values[c(2,5,6,8,9),12])

plot(loadings.negative.low, type = "p", pch = 16, col = "red", ylim = c(-.1,1))
points(loadings.negative.high, type = "p", pch = 17, col = "blue")

save.image(file="AnalysisGnambs2018.RData")

sessionInfo()
```

