---
title: "Illustrations using Mathieu et al. (2015)"
author: "Mike Cheung"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    keep_md: yes
    self_contained: yes
    theme: united
    toc: yes
  pdf_document:
    toc: yes
  word_document: default
editor_options: 
  chunk_output_type: console
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 100)
knitr::opts_chunk$set(message=FALSE)
```
    
```{r, echo=FALSE, eval=FALSE}    
library(metaSEM)

## Figure 1 in the paper
fig1 <- 'f1 =~ x1+x2+x3
         f2 =~ x4+x5+x6
         f1 ~~ 1*f1
         f2 ~~ 1*f2
         f1 ~~ f2'

svg(file="Fig1.svg", width=4, height=4)
plot(fig1, color="yellow")
dev.off()
```    
    
# TSSEM    
## Data preparation
```{r}
library(metaSEM)

## Check the total sample size per correlation
pattern.n(Mathieu15$data, Mathieu15$n)

## Check the number of studies per correlation
pattern.na(Mathieu15$data, show.na=FALSE)
```

## Model 1: no constraint
```{r}
## Stage 1 analysis
tssem1.fit <- tssem1(Mathieu15$data, Mathieu15$n)
summary(tssem1.fit)

## Average correlation matrix
coeffs <- vec2symMat( coef(tssem1.fit, select="fixed"), diag=FALSE )
coeffs

## Heterogeneity variances
heter <- vec2symMat( coef(tssem1.fit, select="random"), diag=FALSE )
heter

## Combine them in a matrix
coeffs[upper.tri(coeffs)] <- 0
heter[lower.tri(heter)] <- 0
combined <- coeffs + heter
diag(combined) <- 1
combined

## Proposed model in lavaan syntax
model1 <- 'C2 ~ c2c*C1 + p2c*P1
           P2 ~ c2p*C1 + p2p*P1
           C1 ~~ c1withp1*P1
           C1 ~~ 1*C1
           P1 ~~ 1*P1
           C2 ~~ c2withp2*P2'

## Display the proposed model
plot(model1, color="green", edge.label.position=0.55)

## Convert the lavaan model to RAM specification
RAM1 <- lavaan2RAM(model1, obs.variables=c("C1", "P1", "C2", "P2"))
RAM1

## Stage 2 analysis
tssem1b.fit <- tssem2(tssem1.fit, RAM=RAM1)
summary(tssem1b.fit)

## Figure 2 in the paper
## svg(file="Fig2.svg", width=4, height=4)
plot(tssem1b.fit, col="yellow", edge.label.position=0.58)
## dev.off()
```

## Model 2: Equality constraints on the path coefficients
```{r}
## Proposed model with equal effects time 1 to time 2
model2 <- 'C2 ~ same*C1 + diff*P1
           P2 ~ diff*C1 + same*P1
           C1 ~~ c1withp1*P1
           C1 ~~ 1*C1
           P1 ~~ 1*P1
           C2 ~~ c2withp2*P2'

## Display the proposed model
plot(model2, color="green", edge.label.position=0.55)

## Convert the lavaan model to RAM specification
RAM2 <- lavaan2RAM(model2, obs.variables=c("C1", "P1", "C2", "P2"))
RAM2

## Stage 2 analysis
tssem2b.fit <- tssem2(tssem1.fit, RAM=RAM2)
summary(tssem2b.fit)

anova(tssem1b.fit, tssem2b.fit)

## Plot the model
plot(tssem2b.fit, col="yellow", edge.label.position=0.60)
```

# OSMASEM
## Data preparation
```{r}
my.df <- Cor2DataFrame(Mathieu15)
    
head(my.df$data)
```

## Model without any moderator
```{r}
osmasem.fit1 <- osmasem(model.name="No moderator", RAM=RAM1, data=my.df)
summary(osmasem.fit1)

## Extract the heterogeneity variance-covariance matrix
diag(VarCorr(osmasem.fit1))

plot(osmasem.fit1, col="yellow", edge.label.position=0.6)
```

## Model with student sample as a moderator on the regression coefficients
```{r}
## Create a matrix with "Student" as a moderator
A1 <- create.modMatrix(RAM1, output="A", "Student")
A1

osmasem.fit2 <- osmasem(model.name="Student sample as a moderator", 
                        RAM=RAM1, Ax=A1, data=my.df)
summary(osmasem.fit2)

## Compare the models with and without the moderator
anova(osmasem.fit2, osmasem.fit1)

## Get the R2 of the moderator
osmasemR2(osmasem.fit2, osmasem.fit1)

## Path coefficients for non-student sample
mxEval(A0, osmasem.fit2$mx.fit)

## Path coefficients for student sample
mxEval(A0+A1, osmasem.fit2$mx.fit)

sessionInfo()
```
